### ISSUE TITLE
Incorrect RPM release version

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/aexpect#51]
It seems that the release version of the 1.5.1 RPM and the SPEC file in the 1.5.1 repo do not correspond:

```
# dnf info python3-aexpect
Last metadata expiration check: 0:43:12 ago on Tue Mar  5 02:24:57 2019.
Available Packages
Name         : python3-aexpect
Version      : 1.5.1
Release      : 1.fc28
Arch         : noarch
Size         : 51 k
Source       : python-aexpect-1.5.1-1.fc28.src.rpm
Repo         : updates
Summary      : A python library to control interactive applications
URL          : https://github.com/avocado-framework/aexpect
License      : GPLv2
Description  : Aexpect is a python library used to control interactive applications, very
             : similar to pexpect. You can use it to control applications such as ssh, scp
             : sftp, telnet, among others.
```
Release here is "1" while release in the spec file is "0":

```
Name: python-%{srcname}
Version: 1.5.1
Release: 0%{?gitrel}%{?dist}
Summary: Aexpect is a python library to control interactive applications
Group: Development/Tools
```

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue: Aexpect rpm version](https://trello.com/c/XJKwnbH4/1499-issue-aexpect-rpm-version)

**Comment by clebergnu** [comment]
@pevogam this is understandable, given that the Fedora packages are really tracked on its own dist-git repo.  We try to keep them in close sync though.  @mmathesius any comments here?

**Comment by mmathesius** [comment]
The [Fedora SPEC file](https://src.fedoraproject.org/rpms/python-aexpect/blob/latest/f/python-aexpect.spec) specifies the `Release` along with the location where the upstream sources can be found (`Source0`)--which happens to also contain a [SPEC file](https://github.com/avocado-framework/aexpect/blob/master/python-aexpect.spec). The Fedora releases increment at their own pace--sometimes initiated by Fedora Release Engineering (such as mass rebuilds)--so there's just no guarantees that the values will be the same.

Also note that `1` rather than `0` is the recommended starting value for `Release` according to the [RPM Packaging Guidelines](https://rpm-packaging-guide.github.io/#preamble-items) and [Fedora Packaging Guidelines](https://docs.fedoraproject.org/en-US/quick-docs/creating-rpm-packages/#con_rpm-spec-file-overview). It is just as well that the upstream SPEC contains `Release: 0` as a possible indication that it's the upstream starting point.

**Comment by pevogam** [comment]
@mmathesius I would generally expect to see RPMs available for download from the Fedora repositories that have a version smaller or equal to the one in the upstream source tree but I guess this excludes the `Release` specification. In this case may I ask what happens if the upstream devs also increment the `Release` count due to packaging-related change in the upstream SPEC file? Does this mean that they are not expected to touch the release version and it should only be modifiable by packagers? The way I understand the second paragraph is that `Release: 0` is the preferred initial value for upstream SPEC files to indicate that no packaging and release changes are done there and a constant throughout the upstream development, correct?

**Comment by mmathesius** [comment]
@pevogam Quite simply, the upstream and Fedora downstream SPEC files are independent. Don't expect the release numbers to be the same. My earlier second paragraph was just a note and random opinion--don't put too much substance into it! :smile:

**Comment by pevogam** [comment]
In any case, I like the idea of using 0 to indicate upstream packager-independent spec. Thanks for the clarification - since everything is clear now I am closing this.
